In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
import time


In [2]:
# Removes warnings for the error messege
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
# Make sparse coulms, fix everything
# Scale the data for svm

In [3]:
data = pd.read_csv(r"book_rating_train.csv", index_col = False, delimiter = ',', header=0)
# X_train = X_full_train.iloc[:,:-1]
Y = data["rating_label"]

label_var = 'rating_label'

# Gets the data types, and removes all int data types
data[label_var], ind2label = pd.factorize(data[label_var])
data = data.select_dtypes(include="number")

# normalize numerical variables
for feature in data:
    scaler = StandardScaler()
    scaler.fit(data[feature].values.reshape(-1,1))
    data[feature] = scaler.transform(data[feature].values.reshape(-1,1))

doc2vec_data_source = "book_text_features_doc2vec"
# Maybe replace names of 0, 1, 2 etc with word vector i
# can't do random forrest with float64, need int64
authors_d2v_test = pd.read_csv(f"{doc2vec_data_source}/test_authors_doc2vec20.csv", index_col = False, delimiter = ',', header=None)
authors_d2v_train = pd.read_csv(f"{doc2vec_data_source}/train_authors_doc2vec20.csv", index_col = False, delimiter = ',', header=None)

desc_d2v_test = pd.read_csv(f"{doc2vec_data_source}/test_desc_doc2vec100.csv", index_col = False, delimiter = ',', header=None)
desc_d2v_train = pd.read_csv(f"{doc2vec_data_source}/train_desc_doc2vec100.csv", index_col = False, delimiter = ',', header=None)

name_d2v_test = pd.read_csv(f"{doc2vec_data_source}/test_name_doc2vec100.csv", index_col = False, delimiter = ',', header=None)
name_d2v_train = pd.read_csv(f"{doc2vec_data_source}/train_name_doc2vec100.csv", index_col = False, delimiter = ',', header=None)

In [4]:
X_train = data.iloc[:,:-1]
# Y = X_full_train["rating_label"]

In [43]:
X = pd.concat([X_train, authors_d2v_train, desc_d2v_train, name_d2v_train], axis=1)

In [44]:
# X = pd.read_csv(f"X_train_data_merged.csv", index_col = False, delimiter = ',', header=None)

In [45]:
# Attemping random dropout
four_rand_sample = Y.loc[Y==4.0].sample(frac=0.1)
four_rand_sample

four_rand_sample.index
X = X.drop(four_rand_sample.index)
Y = Y.drop(four_rand_sample.index)
X.shape, Y.shape

((21442, 444), (21442,))

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [47]:
def SVM(x_train=None, x_test=None, y_train=None, y_test=None, kernel_param="rbf"):
    # Kernals which can be used
    # {‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’}
    clf = svm.SVC(kernel="linear")
    clf.fit(x_train, y_train)

    predictions = clf.predict(x_test)
    # print(predictions)

    describe_data = pd.DataFrame(predictions)
    # print(describe_data.describe())
    
    accuracy = accuracy_score(y_test, predictions)
    print(accuracy)
    
    return clf

SyntaxError: invalid syntax (1342723886.py, line 11)

In [9]:
# Do not normalise the Y label
# Bad things happen >:((((
kernel_list = ["linear", "poly", "rbf", "sigmoid", "precomputed"]
for kernel in kernel_list:
    temp_acc = []
    print(f"Kernel: {kernel}")
    for i in range(4):
        acc = SVM(X_train, X_test, y_train, y_test, kernel_param=kernel)
        temp_acc.append(acc)
        print(f"acc: {acc}")
    print(f"Avg acc: {temp_acc.mean})

[4. 4. 4. ... 4. 4. 4.]
            0
count  4613.0
mean      4.0
std       0.0
min       4.0
25%       4.0
50%       4.0
75%       4.0
max       4.0
0.7112508129200087
Kernel linear, acc: SVC(kernel='linear')
[4. 4. 4. ... 4. 4. 4.]
            0
count  4613.0
mean      4.0
std       0.0
min       4.0
25%       4.0
50%       4.0
75%       4.0
max       4.0
0.7112508129200087
Kernel poly, acc: SVC(kernel='linear')
[4. 4. 4. ... 4. 4. 4.]
            0
count  4613.0
mean      4.0
std       0.0
min       4.0
25%       4.0
50%       4.0
75%       4.0
max       4.0
0.7112508129200087
Kernel rbf, acc: SVC(kernel='linear')
[4. 4. 4. ... 4. 4. 4.]
            0
count  4613.0
mean      4.0
std       0.0
min       4.0
25%       4.0
50%       4.0
75%       4.0
max       4.0
0.7112508129200087
Kernel sigmoid, acc: SVC(kernel='linear')
[4. 4. 4. ... 4. 4. 4.]
            0
count  4613.0
mean      4.0
std       0.0
min       4.0
25%       4.0
50%       4.0
75%       4.0
max       4.0
0.711250812920

In [17]:
clf = svm.SVC(kernel="linear")
clf.fit(X_train, y_train,)

predictions = clf.predict(X_test)
predictions

array([4., 4., 4., ..., 4., 4., 4.])

In [55]:
for i in range(30):
    X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
    data = np.full((4289,), 4.0)
    df = pd.DataFrame(data)
    print(accuracy_score(y_test, df))

0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891
0.6805782233620891


(21442,)

In [13]:
991 / 23063

0.04296925811906517